# Pandas: Creating, Reading and Writing

## Importacion

In [1]:
import pandas as pd

## Creacion de datos

Un dataframe es una tabla. Contiene un array de entradas individuales, cada una con un valor especifivo.
Cada entrada corresponde a una fila y una columna.

In [2]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

Los dataframe pueden tener diferentes tipos de datos, como por ejemplo cadenas de texto.

In [3]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

Utilizamos el pd.DataFrame(), es un constructor que genera los objetos dataframe. La forma de declarar uno nuevo es utilizando un diccionario que sus llaves son el nombre de la columna y sus valores son una lista de entradas (filas).

Normalmente esta indexado de manera ascendente (0,1,2,3,...), pero tambien se puede asignar manualmente sus valores de indice, utilizando index.

In [4]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

### Series

Una series en pandas, es una secuencia de valores de datos, si el dataframe es una tabla, una series es una lista.

Se puede crear una series con nada mas que una lista.

In [5]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

Una serie es un dataframe de una sola columna. Por lo que se puede asignar un nombre a las filas como se vio en las secciones anteriores, utilizando index. Una series no tiene un nombre de columna, tiene un nombre sobre todo.

In [6]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

## Leyendo datos

La mayor parte del tiempo utilizaremos datos que ya existen. 

Los datos se guardan de muchos formatos y formas. El mas basico es el formato CSV. Cuando se abre un documento CSV se ve algo como esto:

- Product A,Product B,Product C,
- 30,21,9,
- 35,34,1,
- 41,11,11

Por lo que un CSV es un formato que separa datos por comas (Comma separated values)

La forma de leer un csv es con pd.read_csv(), ingresando la direccion donde se encuentra el documento o un link para descargar el documento de alguna pagina.

In [11]:
path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_mod2.csv"
df = pd.read_csv(path)
df.head()

,Unnamed: 0.1,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Price-binned,Screen-Full_HD,Screen-IPS_panel
0,0,0,Acer,4,2,1,5,14.0,0.551724,8,256,3.52800,978,Low,0,1
1,1,1,Dell,3,1,1,3,15.6,0.689655,4,256,4.85100,634,Low,1,0
2,2,2,Dell,3,1,1,7,15.6,0.931034,8,256,4.85100,946,Low,1,0
3,3,3,Dell,4,2,1,5,13.3,0.551724,8,128,2.69010,1244,Low,0,1
4,4,4,HP,4,2,1,7,15.6,0.620690,8,256,4.21155,837,Low,1,0

## Funciones basicas

Para obtener el tipo de datos y el conteo de nulos dentro del dataframe utilizamos df.info()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 238 entries, 0 to 237
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        238 non-null    int64
 1   Manufacturer      238 non-null    object
 2   Category          238 non-null    int64
 3   GPU               238 non-null    int64
 4   OS                238 non-null    int64
 5   CPU_core          238 non-null    int64
 6   Screen_Size_inch  238 non-null    float64
 7   CPU_frequency     238 non-null    float64
 8   RAM_GB            238 non-null    int64
 9   Storage_GB_SSD    238 non-null    int64
 10  Weight_pounds     238 non-null    float64
 11  Price             238 non-null    int64
 12  Price-binned      238 non-null    object
 13  Screen-Full_HD    238 non-null    int64
 14  Screen-IPS_panel  238 non-null    int64
dtypes: float64(3), int64(10), object(2)
memory usage: 29.8+ KB

df.describe() muestra algunas estadisticas de las columnas de tipo int y float

In [15]:
df.describe()

,Unnamed: 0,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Screen-Full_HD,Screen-IPS_panel
count,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000,238.000000
mean,118.500000,3.205882,2.151261,1.058824,5.630252,14.688655,0.813822,7.882353,245.781513,4.106221,1462.344538,0.676471,0.323529
std,68.848868,0.776533,0.638282,0.235790,1.241787,1.166045,0.141860,2.482603,34.765316,1.078442,574.607699,0.468809,0.468809
min,0.000000,1.000000,1.000000,1.000000,3.000000,12.000000,0.413793,4.000000,128.000000,1.786050,527.000000,0.000000,0.000000
25%,59.250000,3.000000,2.000000,1.000000,5.000000,14.000000,0.689655,8.000000,256.000000,3.246863,1066.500000,0.000000,0.000000
50%,118.500000,3.000000,2.000000,1.000000,5.000000,15.000000,0.862069,8.000000,256.000000,4.106221,1333.000000,1.000000,0.000000
75%,177.750000,4.000000,3.000000,1.000000,7.000000,15.600000,0.931034,8.000000,256.000000,4.851000,1777.000000,1.000000,1.000000
max,237.000000,5.000000,3.000000,2.000000,7.000000,17.300000,1.000000,16.000000,256.000000,7.938000,3810.000000,1.000000,1.000000

Con includes podemos incluir los datos de tipo object, aunque no se mostrara mucha informacion

In [18]:
df.describe(include='object')

       Manufacturer Price-binned
count           238          238
unique           11            3
top            Dell          Low
freq             71          160

## Indexing y seleccion de datos

Para ver cierta cantidad de datos o datos mas especificos se utiliza df.iloc[], que devuelve todas las filas que tienen las mismas etiquetas que se entrega y devuelve un dataframe con el resultado el cual se puede guardar en otra variable para su uso.

En el ejemplo estamos buscando todas las filas que tienen una categoria numero 4 y elegimos mostrar solo las primeras 5 filas.

In [25]:
df_loc = df.loc[df['Category']==4]
df_loc.head()

,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Price-binned,Screen-Full_HD,Screen-IPS_panel
0,0,Acer,4,2,1,5,14.0,0.551724,8,256,3.52800,978,Low,0,1
3,3,Dell,4,2,1,5,13.3,0.551724,8,128,2.69010,1244,Low,0,1
4,4,HP,4,2,1,7,15.6,0.620690,8,256,4.21155,837,Low,1,0
13,13,Dell,4,2,1,5,14.0,0.551724,8,256,3.74850,1117,Low,1,0
16,16,Dell,4,1,1,7,13.0,0.620690,8,256,3.08700,1213,Low,0,1

Se pueden agregar mas etiquetas para una busqueda mas especifica, como en el ejemplo que estamos buscando todas las filas que contengan Category 4 y Manufacturer Dell.

In [26]:
df_loc2 = df.loc[(df['Category']==4) & (df['Manufacturer']=='Dell')]
df_loc2.head()

,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Price-binned,Screen-Full_HD,Screen-IPS_panel
3,3,Dell,4,2,1,5,13.3,0.551724,8,128,2.69010,1244,Low,0,1
13,13,Dell,4,2,1,5,14.0,0.551724,8,256,3.74850,1117,Low,1,0
16,16,Dell,4,1,1,7,13.0,0.620690,8,256,3.08700,1213,Low,0,1
18,18,Dell,4,2,1,5,15.0,0.551724,8,256,4.14540,1392,Low,0,1
22,22,Dell,4,2,1,7,13.0,0.620690,8,256,2.66805,2095,Medium,0,1

Se pueden utilizar etiquetas enteras si el indice del dataframe consta de numeros enteros

In [27]:
df.loc[0:5, ['GPU', 'OS']]

   GPU  OS
0    2   1
1    1   1
2    1   1
3    2   1
4    2   1
5    1   1

Tambien se puede utilizar df.iloc[], que utiliza las posiciones enteras y ademas puede aceptar una matriz booleana.

Se puede obtener una celda en especifico del dataframe: df.iloc[0,0]

Asimismo se puede obtener un segmento de todo el dataframe: df.iloc[0:4, 2:5]

De las cuales primero se especifica la fila o cantidad de filas y la columna o cantidad de columnas.

In [29]:
df.iloc[0:4, 2:5]

   Category  GPU  OS
0         4    2   1
1         3    1   1
2         3    1   1
3         4    2   1

**¿En qué se diferencian .iloc[] y .loc[]?**

En pandas en Python, la .iloc[] propiedad accede a un grupo de filas y columnas de DataFrame mediante indexación basada en la ubicación de enteros (como df.iloc[0,0]) o matriz booleana.

La df.loc[] propiedad accede a las filas y columnas de DataFrame utilizando sus etiquetas (como df.loc[‘row_1’, ‘column_1’]) o una matriz booleana.

**¿Qué significan las siglas LOC en Python?**

En la biblioteca pandas de Python, "loc" .loc[] significa "ubicación" 

"iloc" .iloc[] significa "ubicación entera". Esto hace referencia al tipo de indexación que utiliza cada propiedad para acceder a las filas y columnas de un DataFrame.

## Filtros Booleanos

Se construye una mascara booleana (serie de True/False) y se usa apara filtrar dilas.

In [30]:
df = pd.DataFrame({
    'producto': ['A', 'B', 'C', 'D'],
    'precio': [100, 200, 150, 300],
    'stock': [10, 5, 8, 2]
}, index=['x', 'y', 'z', 'w'])

De la siguiente manera solo se muestra que filas cumplen con el filtro, pero solo mostrando el valor booleano

In [33]:
mascara = df['precio'] > 150
mascara

x    False
y     True
z    False
w     True
Name: precio, dtype: bool

De la siguiente manera se muestra un dataframe con las filas que cumplen con el filtro

In [34]:
mascara = df[df['precio'] > 150]
mascara

  producto  precio  stock
y        B     200      5
w        D     300      2

Se pueden añadir mas de un filtro, con pandas se usan & (y), | (o), ~ (no) — no and/or/not de Python — y cada condición va entre paréntesis:

Ejemplo con & (and):

In [35]:
df[(df['precio'] > 100) & (df['stock'] < 10)]

  producto  precio  stock
y        B     200      5
z        C     150      8
w        D     300      2

Ejemplo con | (or):

In [36]:
df[(df['producto'] == 'A') | (df['producto'] == 'C')]

  producto  precio  stock
x        A     100     10
z        C     150      8

Ejemplo con ~ (not):

In [37]:
df[~(df['stock'] < 5)]

  producto  precio  stock
x        A     100     10
y        B     200      5
z        C     150      8

Se utiliza .isin() para múltiples valores

In [38]:
df[df['producto'].isin(['A', 'C'])]

  producto  precio  stock
x        A     100     10
z        C     150      8

Se pueden mezclar filtros booleanos con loc

In [39]:
df.loc[df['precio'] > 150, 'producto']

y    B
w    D
Name: producto, dtype: object

In [40]:
df.loc[df['precio'] > 150, ['producto', 'stock']]

  producto  stock
y        B      5
w        D      2

## Ordenamiento

sort_values() - Ordena por el valor de una o mas columnas

In [41]:
df.sort_values('precio')                          # ascendente (default)

  producto  precio  stock
x        A     100     10
z        C     150      8
y        B     200      5
w        D     300      2

In [42]:
df.sort_values('precio', ascending=False)          # descendente

  producto  precio  stock
w        D     300      2
y        B     200      5
z        C     150      8
x        A     100     10

In [43]:
df.sort_values(['stock', 'precio'])                 # múltiples columnas

  producto  precio  stock
w        D     300      2
y        B     200      5
z        C     150      8
x        A     100     10

In [44]:
df.sort_values(['stock', 'precio'], ascending=[True, False])  # orden distinto por columna

  producto  precio  stock
w        D     300      2
y        B     200      5
z        C     150      8
x        A     100     10

sort_index() - Ordena por el índice (nombre de fila), no por los valores:

In [45]:
df.sort_index()

  producto  precio  stock
w        D     300      2
x        A     100     10
y        B     200      5
z        C     150      8

In [46]:
df.sort_index(ascending=False)

  producto  precio  stock
z        C     150      8
y        B     200      5
x        A     100     10
w        D     300      2

Ambos aceptan inplace=True si quieres modificar el DataFrame directamente en vez de devolver uno nuevo 

(aunque en general es más seguro reasignar: df = df.sort_values(...)).

In [ ]:
# Top 5 productos con precio más alto
df.sort_values('precio', ascending=False).head()

  producto  precio  stock
w        D     300      2
y        B     200      5
z        C     150      8
x        A     100     10

In [52]:
# Filtrar solo categoría "producto" con precio > 200
df.loc[(df['producto'].isin(['D', 'B'])) & (df['precio'] > 180)]

  producto  precio  stock
y        B     200      5
w        D     300      2

In [54]:
# Seleccionar solo columnas relevantes de las primeras 5 filas
df.iloc[:5, [0, 2]]

  producto  stock
x        A     10
y        B      5
z        C      8
w        D      2

Utilizando .query()

In [57]:
df.query('precio > 180')

  producto  precio  stock
y        B     200      5
w        D     300      2

In [59]:
df.query('producto in ("D","B") and precio > 180')

  producto  precio  stock
y        B     200      5
w        D     300      2

# Conclusion

En esta práctica trabajé con las estructuras fundamentales de Pandas: Series y DataFrame, 
y cómo cargar datos tabulares reales con `read_csv()`. Exploré un dataset público de precios 
de laptops usando `head()`, `info()` y `describe()` para entender su estructura antes de 
analizarlo.

También practiqué selección e indexado con `loc` (por etiqueta) e `iloc` (por posición), 
filtros booleanos combinando condiciones con `&`, `|` y `~`, el uso de `.isin()` y `.query()` 
para filtros más legibles, y ordenamiento con `sort_values()` y `sort_index()`.

Estas herramientas son la base para cualquier análisis exploratorio de datos (EDA), y las 
aplicaré directamente sobre mi dataset de ventas retail en los próximos días.