# Limpieza de datos

In [391]:
import pandas as pd

## Traer datos del cuaderno de importacion
Se utiliza el siguiente comando para traer todos los datos, variables, etc. Del cuaderno anterior para utilizarlos en este cuaderno en el siguiente proceso que es el de limpieza.

In [392]:
%run 01_importacion_datos.ipynb

Atenciones:  (168530, 7)
Citas:  (220000, 9)
Diagnosticos:  (168530, 5)
Especialidades:  (12, 2)
Medicos:  (150, 5)
Pacientes:  (20000, 7)
Servicios:  (24, 4)

## Verificacion de nulos
Se realiza una verificacion a todos los dataframe creados anteriormente para ver si tienen valores nulos o faltantes.

Ya que son datos creados artificialmente no tienen datos nulos, la unica columna con nulos es hora_atencion de la tabla citas, ya que solo las citas con el estado 'Atendidas' tienen ese dato, por lo que el resto esta como dato faltante.

In [393]:
# Nulos de la tabla atenciones
df_atenciones.isnull().sum()

atencion_id         0
cita_id             0
fecha_atencion      0
duracion_minutos    0
tiempo_espera       0
costo_atencion      0
satisfaccion        0
dtype: int64

In [394]:
# Nulos de la tabla citas
df_citas.isnull().sum()

cita_id              0
paciente_id          0
medico_id            0
servicio_id          0
fecha_cita           0
hora_agendada        0
hora_atencion    51470
estado               0
canal_reserva        0
dtype: int64

In [395]:
# Nulos de la tabla diagnosticos
df_diagnosticos.isnull().sum()

diagnostico_id    0
atencion_id       0
codigo_cie10      0
diagnostico       0
gravedad          0
dtype: int64

In [396]:
# Nulos de la tabla especialidades
df_especialidades.isnull().sum()

especialidad_id    0
especialidad       0
dtype: int64

In [397]:
# Nulos de la tabla medicos
df_medicos.isnull().sum()

medico_id          0
nombre             0
especialidad_id    0
fecha_ingreso      0
tipo_contrato      0
dtype: int64

In [398]:
# Nulos de la tabla pacientes
df_pacientes.isnull().sum()

paciente_id         0
nombre              0
fecha_nacimiento    0
sexo                0
comuna              0
tipo_seguro         0
fecha_registro      0
dtype: int64

In [399]:
# Nulos de la tabla servicios
df_servicios.isnull().sum()

servicio_id    0
servicio       0
categoria      0
precio         0
dtype: int64

## Verificacion de duplicados

Se utiliza el id de cada columna para realizar la verificacion.

In [400]:
print('Atenciones:',df_atenciones.duplicated(subset='atencion_id').sum())
print('Citas:',df_citas.duplicated(subset='cita_id').sum())
print('Diagnosticos:',df_diagnosticos.duplicated(subset='diagnostico_id').sum())
print('Especialidades:',df_especialidades.duplicated(subset='especialidad_id').sum())
print('Medicos:',df_medicos.duplicated(subset='medico_id').sum())
print('Pacientes:',df_pacientes.duplicated(subset='paciente_id').sum())
print('Servicios:',df_servicios.duplicated(subset='servicio_id').sum())

Atenciones: 0
Citas: 0
Diagnosticos: 0
Especialidades: 0
Medicos: 0
Pacientes: 0
Servicios: 0

## Tipos de datos
Esta seccion es para ver y corregir el tipo de datos de las diferentes columnas en caso de ser necesario.

In [401]:
df_atenciones.dtypes

atencion_id           int64
cita_id               int64
fecha_atencion       object
duracion_minutos      int64
tiempo_espera         int64
costo_atencion      float64
satisfaccion          int64
dtype: object

En esta tabla de atenciones la fecha_atencion deberia ser datetime, en cambio es tipo object. Por lo que se cambiara su tipo y esto asi con cada una de las tablas en caso de ser necesario.

In [402]:
df_atenciones['fecha_atencion'] = pd.to_datetime(df_atenciones['fecha_atencion'])
df_atenciones['fecha_atencion'].dtypes

dtype('<M8[s]')

In [403]:
df_citas.dtypes

cita_id           int64
paciente_id       int64
medico_id         int64
servicio_id       int64
fecha_cita       object
hora_agendada    object
hora_atencion    object
estado              str
canal_reserva       str
dtype: object

In [404]:
df_citas['fecha_cita'] = pd.to_datetime(df_citas['fecha_cita'])
df_citas['fecha_cita'].dtypes

dtype('<M8[s]')

En esta oportunidad para realizar ciertos calculos respecto a la hora o filtrados, convertiremos este objeto a tipo hora.

In [405]:
df_citas['hora_agendada'] = pd.to_timedelta(df_citas['hora_agendada'].astype(str))
df_citas['hora_agendada'].dtypes

dtype('<m8[us]')

In [406]:
df_citas['hora_atencion'] = pd.to_timedelta(df_citas['hora_atencion'].astype(str))
df_citas['hora_atencion'].dtypes

dtype('<m8[us]')

In [407]:
df_citas['hora_atencion'].isnull().sum()

np.int64(51470)

In [408]:
df_diagnosticos.dtypes

diagnostico_id    int64
atencion_id       int64
codigo_cie10        str
diagnostico         str
gravedad            str
dtype: object

In [409]:
df_especialidades.dtypes

especialidad_id    int64
especialidad         str
dtype: object

In [410]:
df_medicos.dtypes

medico_id           int64
nombre                str
especialidad_id     int64
fecha_ingreso      object
tipo_contrato         str
dtype: object

In [411]:
df_medicos['fecha_ingreso'] = pd.to_datetime(df_medicos['fecha_ingreso'])
df_medicos['fecha_ingreso'].dtypes

dtype('<M8[s]')

In [412]:
df_pacientes.dtypes

paciente_id          int64
nombre                 str
fecha_nacimiento    object
sexo                   str
comuna                 str
tipo_seguro            str
fecha_registro      object
dtype: object

In [413]:
df_pacientes['fecha_nacimiento'] = pd.to_datetime(df_pacientes['fecha_nacimiento'])
df_pacientes['fecha_nacimiento'].dtypes

dtype('<M8[s]')

In [414]:
df_pacientes['fecha_registro'] = pd.to_datetime(df_pacientes['fecha_registro'])
df_pacientes['fecha_registro'].dtypes

dtype('<M8[s]')

In [415]:
df_servicios.dtypes

servicio_id      int64
servicio           str
categoria          str
precio         float64
dtype: object

## Revision de tipo consistencia en datos categoricos

In [416]:
df_citas['estado'].unique()

<StringArray>
['Atendida', 'No asistió', 'Cancelada', 'Reprogramada']
Length: 4, dtype: str

In [417]:
df_citas['canal_reserva'].unique()

<StringArray>
['App', 'Call Center', 'Web', 'Presencial']
Length: 4, dtype: str

In [418]:
df_pacientes['sexo'].unique()

<StringArray>
['Femenino', 'Masculino']
Length: 2, dtype: str

In [419]:
df_pacientes['tipo_seguro'].unique()

<StringArray>
['Isapre', 'Fonasa', 'Particular']
Length: 3, dtype: str

In [420]:
df_medicos['tipo_contrato'].unique()

<StringArray>
['Part-time', 'Planta', 'Honorarios']
Length: 3, dtype: str

In [421]:
df_diagnosticos['diagnostico'].unique()

<StringArray>
[                      'Vértigo',          'Rinofaringitis aguda',
               'Dolor articular',            'Ictericia neonatal',
                'Catarata senil',               'Vaginitis aguda',
         'Hipertensión esencial',             'Diarrea funcional',
                      'Obesidad',      'Fractura de radio distal',
         'Menstruación excesiva',                  'Otitis media',
           'Esguince de tobillo',         'Fibrilación auricular',
           'Esguince de rodilla',             'Carcinoma de piel',
 'Isquemia cerebral transitoria',            'Trastorno muscular',
                       'Cefalea',                     'Epilepsia',
  'Enfermedad isquémica crónica',                       'Migraña',
        'Fiebre no especificada',  'Infección respiratoria aguda',
                       'Lumbago',         'Trastorno de ansiedad',
            'Dermatitis atópica',     'Complicación del embarazo',
             'Sinusitis crónica',            'Episodio depresivo',
                          'Acné',             'Trastorno bipolar',
                        'Miopía',                'Hipotiroidismo',
               'Diabetes tipo 2',                      'Glaucoma']
Length: 36, dtype: str

In [422]:
df_diagnosticos['gravedad'].unique()

<StringArray>
['Moderada', 'Leve', 'Grave']
Length: 3, dtype: str

## Tabla analitica unificada

In [423]:
tb_analitica = pd.merge(df_citas, df_atenciones, on='cita_id', how='left')
tb_analitica.head(2)

,cita_id,paciente_id,medico_id,servicio_id,fecha_cita,hora_agendada,hora_atencion,estado,canal_reserva,atencion_id,fecha_atencion,duracion_minutos,tiempo_espera,costo_atencion,satisfaccion
0,1,15306,53,6,2023-02-05,0 days 17:30:00,0 days 18:07:00,Atendida,App,1.0,2023-02-05,28.0,37.0,51200.0,4.0
1,2,1708,91,1,2024-05-07,0 days 14:45:00,0 days 14:59:00,Atendida,Call Center,2.0,2024-05-07,21.0,14.0,14900.0,5.0

In [424]:
tb_analitica = pd.merge(tb_analitica, df_pacientes.rename(columns={'nombre':'nombre paciente'}), on='paciente_id', how='left')
tb_analitica.head(2)

,cita_id,paciente_id,medico_id,servicio_id,fecha_cita,hora_agendada,hora_atencion,estado,canal_reserva,atencion_id,...,duracion_minutos,tiempo_espera,costo_atencion,satisfaccion,nombre paciente,fecha_nacimiento,sexo,comuna,tipo_seguro,fecha_registro
0,1,15306,53,6,2023-02-05,0 days 17:30:00,0 days 18:07:00,Atendida,App,1.0,...,28.0,37.0,51200.0,4.0,Scarlet Karen Vera Calderón,1940-09-21,Femenino,Cerro Navia,Fonasa,2025-06-19
1,2,1708,91,1,2024-05-07,0 days 14:45:00,0 days 14:59:00,Atendida,Call Center,2.0,...,21.0,14.0,14900.0,5.0,Adrián Morales García,2017-07-05,Masculino,Providencia,Isapre,2025-05-14

In [425]:
tb_analitica = pd.merge(tb_analitica, df_medicos.rename(columns={'nombre':'nombre medico'}), on='medico_id', how='left')
tb_analitica.head(2)

,cita_id,paciente_id,medico_id,servicio_id,fecha_cita,hora_agendada,hora_atencion,estado,canal_reserva,atencion_id,...,nombre paciente,fecha_nacimiento,sexo,comuna,tipo_seguro,fecha_registro,nombre medico,especialidad_id,fecha_ingreso,tipo_contrato
0,1,15306,53,6,2023-02-05,0 days 17:30:00,0 days 18:07:00,Atendida,App,1.0,...,Scarlet Karen Vera Calderón,1940-09-21,Femenino,Cerro Navia,Fonasa,2025-06-19,Dr(a). Katherine Margarita González Rebolledo,10,2017-12-20,Planta
1,2,1708,91,1,2024-05-07,0 days 14:45:00,0 days 14:59:00,Atendida,Call Center,2.0,...,Adrián Morales García,2017-07-05,Masculino,Providencia,Isapre,2025-05-14,Dr(a). Esteban Daniel Hernández Cáceres,1,2021-03-04,Part-time

In [426]:
tb_analitica = pd.merge(tb_analitica, df_especialidades, on='especialidad_id', how='left')
tb_analitica.head(2)

,cita_id,paciente_id,medico_id,servicio_id,fecha_cita,hora_agendada,hora_atencion,estado,canal_reserva,atencion_id,...,fecha_nacimiento,sexo,comuna,tipo_seguro,fecha_registro,nombre medico,especialidad_id,fecha_ingreso,tipo_contrato,especialidad
0,1,15306,53,6,2023-02-05,0 days 17:30:00,0 days 18:07:00,Atendida,App,1.0,...,1940-09-21,Femenino,Cerro Navia,Fonasa,2025-06-19,Dr(a). Katherine Margarita González Rebolledo,10,2017-12-20,Planta,Otorrinolaringología
1,2,1708,91,1,2024-05-07,0 days 14:45:00,0 days 14:59:00,Atendida,Call Center,2.0,...,2017-07-05,Masculino,Providencia,Isapre,2025-05-14,Dr(a). Esteban Daniel Hernández Cáceres,1,2021-03-04,Part-time,Medicina General

In [427]:
tb_analitica = pd.merge(tb_analitica, df_servicios, on='servicio_id', how='left')
tb_analitica.head(2)

,cita_id,paciente_id,medico_id,servicio_id,fecha_cita,hora_agendada,hora_atencion,estado,canal_reserva,atencion_id,...,tipo_seguro,fecha_registro,nombre medico,especialidad_id,fecha_ingreso,tipo_contrato,especialidad,servicio,categoria,precio
0,1,15306,53,6,2023-02-05,0 days 17:30:00,0 days 18:07:00,Atendida,App,1.0,...,Fonasa,2025-06-19,Dr(a). Katherine Margarita González Rebolledo,10,2017-12-20,Planta,Otorrinolaringología,Ecografía Obstétrica,Imagenología,50000.0
1,2,1708,91,1,2024-05-07,0 days 14:45:00,0 days 14:59:00,Atendida,Call Center,2.0,...,Isapre,2025-05-14,Dr(a). Esteban Daniel Hernández Cáceres,1,2021-03-04,Part-time,Medicina General,Consulta General,Consulta,15000.0

In [428]:
tb_analitica = pd.merge(tb_analitica, df_diagnosticos, on='atencion_id', how='left')
tb_analitica.head(2)

,cita_id,paciente_id,medico_id,servicio_id,fecha_cita,hora_agendada,hora_atencion,estado,canal_reserva,atencion_id,...,fecha_ingreso,tipo_contrato,especialidad,servicio,categoria,precio,diagnostico_id,codigo_cie10,diagnostico,gravedad
0,1,15306,53,6,2023-02-05,0 days 17:30:00,0 days 18:07:00,Atendida,App,1.0,...,2017-12-20,Planta,Otorrinolaringología,Ecografía Obstétrica,Imagenología,50000.0,1.0,H81,Vértigo,Moderada
1,2,1708,91,1,2024-05-07,0 days 14:45:00,0 days 14:59:00,Atendida,Call Center,2.0,...,2021-03-04,Part-time,Medicina General,Consulta General,Consulta,15000.0,2.0,J00,Rinofaringitis aguda,Leve

In [429]:
tb_analitica.isnull().sum()

cita_id                 0
paciente_id             0
medico_id               0
servicio_id             0
fecha_cita              0
hora_agendada           0
hora_atencion       51470
estado                  0
canal_reserva           0
atencion_id         51470
fecha_atencion      51470
duracion_minutos    51470
tiempo_espera       51470
costo_atencion      51470
satisfaccion        51470
nombre paciente         0
fecha_nacimiento        0
sexo                    0
comuna                  0
tipo_seguro             0
fecha_registro          0
nombre medico           0
especialidad_id         0
fecha_ingreso           0
tipo_contrato           0
especialidad            0
servicio                0
categoria               0
precio                  0
diagnostico_id      51470
codigo_cie10        51470
diagnostico         51470
gravedad            51470
dtype: int64

In [430]:
tb_analitica.columns

Index(['cita_id', 'paciente_id', 'medico_id', 'servicio_id', 'fecha_cita',
       'hora_agendada', 'hora_atencion', 'estado', 'canal_reserva',
       'atencion_id', 'fecha_atencion', 'duracion_minutos', 'tiempo_espera',
       'costo_atencion', 'satisfaccion', 'nombre paciente', 'fecha_nacimiento',
       'sexo', 'comuna', 'tipo_seguro', 'fecha_registro', 'nombre medico',
       'especialidad_id', 'fecha_ingreso', 'tipo_contrato', 'especialidad',
       'servicio', 'categoria', 'precio', 'diagnostico_id', 'codigo_cie10',
       'diagnostico', 'gravedad'],
      dtype='str')

## Variables derivadas

In [ ]:
tb_analitica['edad paciente en cita'] = ((tb_analitica['fecha_cita'] - tb_analitica['fecha_nacimiento']).dt.days // 365.25).astype(int)
tb_analitica['edad paciente en cita'].head()

0    82
1     6
2    79
3    40
4    83
Name: edad paciente en cita, dtype: int64

In [ ]:
tb_analitica['dia semana cita'] = tb_analitica['fecha_cita'].dt.day_name(locale='es_ES')
tb_analitica['dia semana cita'].head()

0      Domingo
1       Martes
2    Miércoles
3        Lunes
4      Domingo
Name: dia semana cita, dtype: str

In [446]:
tb_analitica[tb_analitica['edad paciente en cita'] < 0].shape

(4996, 35)

## Tranformar la tabla unificada a CSV

In [451]:
from pathlib import Path

# Detecta el directorio de trabajo actual del notebook
BASE_DIR = Path.cwd()

# Construye la ruta hacia la carpeta 'data'
ruta_guardado = BASE_DIR.parent / 'data' / 'tabla_unificada.csv'

tb_analitica.to_csv(ruta_guardado, index=False, encoding='utf-8')